# # Use the official Node.js image as the base image
# FROM node:14

# # Set the working directory
# WORKDIR /app

# # Copy the package.json and package-lock.json files
# COPY package*.json ./

# # Install the dependencies
# RUN npm install

# # Copy the rest of the application files
# COPY . .

# # Build the React application
# RUN npm run build

# # Use a lightweight web server to serve the application
# FROM nginx:alpine
# COPY --from=0 /app/build /usr/share/nginx/html

# # Expose port 80
# EXPOSE 80

# # Start Nginx server
# CMD ["nginx", "-g", "daemon off;"]


# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
# Adding retry mechanism for npm install
RUN npm install --retry=5 --no-optional

# Copy the rest of the application to the working directory
COPY . .

# Build the application
RUN npm run build

# Use a smaller nginx image to serve the build
FROM nginx:alpine
COPY --from=0 /app/build /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start nginx server
CMD ["nginx", "-g", "daemon off;"]
